version: "3.8"
services:
  manabi:
    container_name: manabi
    build: ./
    working_dir: "/manabi"
    ports:
      - "3000:3000"
      - "24678:24678"
    depends_on:
      - redis
      - db
    volumes:
      - ./:/manabi
      - /manabi/node_modules/
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: manabi
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data: